### ISSUE TITLE
Missing DLLs from installation

### ISSUE THREAD

**Issue by ggtylerr** [callisto-jovy/viddroid_desktop#2]
The latest release seems to be missing DLLs from the setup:
![image](https://github.com/callisto-jovy/viddroid_desktop/assets/28498877/54ad9176-59c0-4dc6-bbe2-d4f67b43b872)
The portable version seems to work though.

**Comment by callisto-jovy** [comment]
Hey! Thank you for your interest in the project :). 
Firstly, I'd like to say that the "latest" builds are outdated, dependency- and code-wise. As I have been busy with another project of mine, the progress on the project has slowed down and I missed out on rebuilding the project & installer. I will build a new release version pretty soon (in a few hours probably) so that the build is as fresh as possible... If you find any bugs in the program itself, feel free to open a new issue!

**Comment by callisto-jovy** [comment]
So, turns out that my build script was faulty and did not include the necessary DLLs. I have a new release prepared!
