### ISSUE TITLE
Development status?

### ISSUE THREAD

**Issue by jackuars7** [callisto-jovy/viddroid_desktop#4]
Has the development for this application stopped? This looks like a decent software. Since Cloudstream is not available on Windows and Microsoft stopped supporting WSA, there seems to be no other alternative on Windows. 

Have you been able to work on your roadmap items especially support for custom providers?

**Comment by callisto-jovy** [comment]
Well, the development of this app has not stopped - however, it's very, very stale. 
The application has always been a passion project of mine, that I created in order to not have to deal with WSL and Cloudstream on desktop. If demand is there, I will continue developing Viddroid; If you (and/or others) are willing to contribute, I'd be very happy :).

**Comment by callisto-jovy** [comment]
As to your question about the custom providers: no, I wasn't able to make progress on that. In the beginning, I thought about implementing a custom scripting language, but now, I'd much rather have a DSL or - even better - embedded scripting (i.e. Lua). 
Unfortunately, I don't know which scripting language would be best for developers wanting to develop custom plugins, so I've never come around to that.
